# Generated by Django 2.0.2 on 2018-04-01 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_candidate_election'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballot',
            name='name',
        ),
        migrations.AddField(
            model_name='ballot',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Election'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='question_text',
            field=models.CharField(default='Default question', max_length=200),
        ),
    ]
