# Generated by Django 2.0.2 on 2018-03-26 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('party', models.CharField(max_length=20)),
                ('number_of_votes', models.IntegerField()),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Ballot')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('type', models.CharField(max_length=20)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PollWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_location', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('date', models.DateTimeField(verbose_name='date voted')),
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Ballot')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_number', models.CharField(max_length=50)),
                ('voter_status', models.CharField(max_length=50)),
                ('date_registered', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=10)),
                ('zip', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('precinct', models.CharField(max_length=20)),
                ('precinct_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Voter'),
        ),
    ]
